sudo: required

before_script:
  - git config --global user.email "iblech@web.de"
  - git config --global user.name "Ingo Blechschmidt (via Travis)"
  - mkdir -m 700 -p $HOME/.ssh
  - echo "$SSH_DEPLOY_KEY" | base64 -d > $HOME/.ssh/id_rsa.pub

script:
  - ./deploy.sh git@github.com:luga-ev/website.git

cache:
  directories:
    - $HOME/.luga-website-cache
